---
# https://crsh.github.io/papaja_man/index.html

title             : "A Simple, Dynamic Extension of Temporal Motivation Theory"
shorttitle        : "GOAL SAMPLING"

author: 
  - name          : "Christopher R. Dishop"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "316 Physics Rd #348, East Lansing, MI 48824"
    email         : "dishopch@msu.edu"


affiliation:
  - id            : "1"
    institution   : "Michigan State University"


author_note: |
  Christopher R. Dishop, Department of Psychology, Michigan State University

abstract: |
  Steel and Konig's (2006) temporal motivation theory (TMT) has been criticized for its static representation and neglect of the environment. In this paper, I develop goal sampling theory (GST) to appease these criticisms and extend our understanding of goal choices beyond momentary preferences and into dynamic updating and global sampling behavior across time. GST draws from temporal motivational theory (TMT), sampling models of impression formation, and organizational theory on how the environment constrains behavior and situates aspects of each into a formal representation of goal sampling. Doing so addresses the limitations of our prior thinking, introduces new concepts and predictions, and provides a mathematical framework that lends itself to computational modeling.
  

bibliography      : ["references.bib"]

figsintext        : no
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : yes

lang              : "english"
class             : "man"
output            : papaja::apa6_pdf
---

```{r load_packages, include = FALSE}
library("papaja")
```

```{r analysis_preferences}
# Seed for random number generation
set.seed(42)
```

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.path = 'figures/', echo = FALSE, warning = FALSE, message = FALSE)
```


```{r child = 'goal_choice_sampling.Rmd'}
```


\newpage

# References
```{r create_references}
r_refs(file = "references.bib")
```

\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
