---
# https://crsh.github.io/papaja_man/index.html

title             : "Conclusions Follow Assumptions, Not Statistics. Directionality Inference in Longitudinal Research"
shorttitle        : "DIRECTIONALITY INFERENCE"

author: 
  - name          : "Christopher R. Dishop"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "316 Physics Rd #348, East Lansing, MI 48824"
    email         : "dishopch@msu.edu"
  - name          : "Richard P. DeShon"
    affiliation   : "1"

affiliation:
  - id            : "1"
    institution   : "Michigan State University"


author_note: |
  Christopher R. Dishop, Department of Psychology, Michigan State University; Richard P. DeShon, Department of Psychology, Michigan State University.

abstract: |
  Increasing interest in modeling dynamic processes is drawing attention toward statistical routines and away from assumptions as the bedrock for causal inference. We review assumptions that are important for drawing inferences from both static and longitudinal designs. We then use Monte Carlo simulations to illustrate that statistical models do little to reveal the nature of the world without underlying assumptions. A point of ambiguity pulled from the literature concerning causal directionality will be used as a driving example throughout, but general notions of causal inference will need attention as our interest in dynamic processes matures.
  
keywords          : "causality, reciprocal causation, longitudinal, dynamics, statistical models"
wordcount         : "95"

bibliography      : ["references.bib"]

figsintext        : no
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : yes

lang              : "english"
class             : "man"
output            : papaja::apa6_pdf
---

```{r load_packages, include = FALSE}
library("papaja")
```

```{r analysis_preferences}
# Seed for random number generation
set.seed(42)
```

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.path = 'figures/', echo = FALSE, warning = FALSE, message = FALSE)
```


```{r child = '1_intro_Rev2.Rmd'}
```


```{r child = '2_Method_Rev1.Rmd'}
```


```{r child = '3_Results_Rev1.Rmd'}
```


```{r child = '4_Discussion_Rev1.Rmd'}
```

\newpage

# References
```{r create_references}
r_refs(file = "references.bib")
```

\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
